In [5]:
d={1:"akash", 2:"pradahan",3:"biky"}
d1=dict(sorted(d.items()))
print(d1)

{1: 'akash', 2: 'pradahan', 3: 'biky'}


In [11]:
import numpy as np
arr=np.random.randint(1,20,10)
mdn=np.median(arr)
print(arr)
mdn

[19 10  1  1 12  1 15 16  1 11]


10.5

In [22]:
arr1=np.array([[[1,2,3],[9,2,1]]])
arr1

array([[[1, 2, 3],
        [9, 2, 1]]])

In [13]:
npt=np.empty((2,3))
npt

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
ar=np.array([1,2,7,12,3,4])
print(np.sort(ar))
print(arr1)
print(np.sort(arr1,axis=1))


[ 1  2  3  4  7 12]
[[[1 2 3]
  [9 2 1]]]
[[[1 2 1]
  [9 2 3]]]


In [31]:
ar.reshape([3,-1])
ar.ravel()
ar>5

array([False, False,  True,  True, False, False])

In [51]:
np.diff(ar)

array([ 1,  5,  5, -9,  1])

In [43]:
print(ar)
arr1[1:,0:2]

[ 1  2  7 12  3  4]


array([], shape=(0, 2, 3), dtype=int32)

In [44]:
arr = np.arange(24).reshape(6,4)

#view NumPy array
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [45]:
arr[1:4,0:3]

array([[ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [46]:
arr[:,:1]

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20]])

In [50]:
arr2 = np.array([1.23, 4.56, 7.89])
np.trunc(arr2)

array([1., 4., 7.])

In [61]:
arr3=np.array([12,23,1,45,6])
print(np.extract(arr3>10,arr3))

[12 23 45]


In [56]:
np.argmax(arr3)

3

In [59]:
np.nonzero(arr3)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [62]:
np.shape(arr3)

(5,)

dtype('int32')

In [65]:
dict2 = {'banana': 3, 'apple': 1, 'orange': 2, 'grape': 4}

# Sort the dictionary by keys
sorted_dict = dict(sorted(dict2.items()))

print(sorted_dict)

{'apple': 1, 'banana': 3, 'grape': 4, 'orange': 2}


In [67]:
l1 = [12, 23]
l2 = [34, 45]
l3 = l1 + l2
print(l3)

l3 = [x for x in l3 if x > 20]
print(l3)

# Use a different variable name for the sum calculation
sum_of_elements = sum(l3)
avr = sum_of_elements / len(l3)
print(f"Sum = {sum_of_elements}, Average = {avr}")


[12, 23, 34, 45]
[23, 34, 45]
Sum = 102, Average = 34.0
